import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  winScriptSidebar: [{type: 'autogenerated', dirName: 'windows-script'}],
  winGuiSidebar: [{type: 'autogenerated', dirName: 'windows-gui'}],
  winSetupSidebar: [{type: 'autogenerated', dirName: 'windows-setup'}],

  softwaresSidebar: [{type: 'autogenerated', dirName: 'softwares'}],
  majorsoftwaresSidebar: [{type: 'autogenerated', dirName: 'major-softwares'}],
  appsSidebar: [{type: 'autogenerated', dirName: 'apps'}],

  linuxadminSidebar: [{type: 'autogenerated', dirName: 'linux-admin'}],
  linuxdesktopSidebar: [{type: 'autogenerated', dirName: 'linux-desktop'}],
  englishSidebar: [{type: 'autogenerated', dirName: 'english'}]


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
